# Generated by Django 3.1.1 on 2020-11-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_subject_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='undo_attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='undo_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='undo_total',
            field=models.IntegerField(default=0),
        ),
    ]
